### ISSUE TITLE
[XML] String attributes not updated properly

### ISSUE THREAD

**Issue by jeryaiwei** [REAndroid/ARSCLib#23] opened 2023-03-29 06:26 UTC
AndroidManifest.xml
        
        <?xml version="1.0" encoding="utf-8"?>
        <manifest
	        xmlns:android="http://schemas.android.com/apk/res/android"
	        android:versionCode="1"
	        android:versionName="1.0"
	        android:compileSdkVersion="28"
	        android:compileSdkVersionCodename="9"
	        package="com.web2apk"
	        platformBuildVersionCode="28"
	        platformBuildVersionName="9"
	        >
	        <uses-sdk
		        android:minSdkVersion="16"
		        android:targetSdkVersion="27"
		        >
	        </uses-sdk>
	        <uses-permission
		        android:name="android.permission.INTERNET"
		        >
	        </uses-permission>
	        <application
		        android:label="@7F040000"
		        android:icon="@7F030000"
		        android:allowBackup="true"
		        android:supportsRtl="true"
		        android:usesCleartextTraffic="true"
		        >
		        <activity
			        android:name="com.web2apk.MainActivity"
			        android:screenOrientation="6"
			        >
			        <intent-filter
				        >
				        <action
					        android:name="android.intent.action.MAIN"
					        >
				        </action>
				        <category
					        android:name="android.intent.category.LAUNCHER"
					        >
				        </category>
			        </intent-filter>
		        </activity>
	        </application>
        </manifest>

i want to set packagename = "com.web2apk.main"

        AndroidManifestBlock manifestBlock = AndroidManifestBlock.load(new File("AndroidManifest.xml"));

        String oldpack = manifestBlock.getPackageName();
        System.out.println( manifestBlock.getPackageName());
        manifestBlock.setPackageName("com.web2apk.main");

        manifestBlock.refresh();

        manifestBlock.writeBytes(new File("out.xml"));;

output  use xml2axml

       <?xml version="1.0" encoding="utf-8"?>
      <manifest
	      xmlns:android="http://schemas.android.com/apk/res/android"
	      android:versionCode="1"
	      android:versionName="1.0"
	      android:compileSdkVersion="28"
	      android:compileSdkVersionCodename="9"
	      package=""
	      platformBuildVersionCode="28"
	      platformBuildVersionName="9"
	      >
	      <uses-sdk
		      android:minSdkVersion="16"
		      android:targetSdkVersion="27"
		      >
	      </uses-sdk>
	      <uses-permission
		      android:name="android.permission.INTERNET"
		      >
	      </uses-permission>
	      <application
		      android:label="@7F040000"
		      android:icon="@7F030000"
		      android:debuggable="true"
		      android:allowBackup="true"
		      android:supportsRtl="true"
		      android:usesCleartextTraffic="true"
		      >
		      <activity
			      android:name="com.web2apk.MainActivity"
			      android:screenOrientation="6"
			      >
			      <intent-filter
				      >
				      <action
					      android:name="android.intent.action.MAIN"
					      >
				      </action>
				      <category
					      android:name="android.intent.category.LAUNCHER"
					      >
				      </category>
			      </intent-filter>
		      </activity>
	      </application>
      </manifest>

**Comment by REAndroid** [comment] 2023-03-29 15:08
- Do you used the latest commit or release?
- Attach your ```original.xml``` and ```modified.xml```

**Comment by jeryaiwei** [comment] 2023-03-30 02:13
> * Do you used the latest commit or release?
> * Attach your `original.xml` and `modified.xml`

i used the latest commit; 

original.xml [AndroidManifest.xml.zip](https://github.com/REAndroid/ARSCLib/files/11107042/AndroidManifest.xml.zip)

modified.xml [out.xml.zip](https://github.com/REAndroid/ARSCLib/files/11107049/out.xml.zip)

xml2axml [xml2axml.jar.zip](https://github.com/REAndroid/ARSCLib/files/11107097/xml2axml.jar.zip)

java -jar xml2axml.jar d ./out.xml ./out1.xml

out1.xml [out1.xml.zip](https://github.com/REAndroid/ARSCLib/files/11107103/out1.xml.zip)

**Comment by REAndroid** [comment] 2023-03-30 11:35
The problem is fixed now check the latest commit

**Closed** 2023-04-27 18:14 UTC
Labels: bug
